name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'app/api/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package -DskipTests --file app/api/pom.xml

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: |
        aws s3 cp app/api/target/*.jar s3://qwikcalai-artifacts/backend/
        aws s3 cp app/api/target/*.jar s3://qwikcalai-artifacts/backend-latest.jar
